#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100
n=1

while [[ $n -le 100 ]]
do
	if [ $((n % 3)) -eq 0 ]
	then
	if [ $((n % 5)) -eq 0 ]
	then
	echo "FizzBuzz"
	else 
	echo "Fizz"
	fi
	elif [ $((n % 5)) -eq 0 ]
	then
	echo "Buzz"
else
echo "$n"
fi
((n++))
done	

