#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS. The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO
# var1Username var2Password var3User ID (UID) var4Group ID (GID) var5User ID Info (GECOS) var6Home directory var7Command/shell

while IFS=: read -r var1 var2 var3 var4 var5 var6 var7 
do
	echo "The user $var1 is part of the $var4 gang, lives in $var6 and rides $var7. $var3's place is protected by the passcode $var2, more info about the user here: $var5"
done < "/etc/passwd"
