#!/usr/bin/env bash
# defines a ver number in 1 them until var aprouch to 10 print Best School and defines that munber increase one to one 
number=1
until [[ $number -eq 10 ]]
do
  echo Best School
  ((number++))
done
