#!/usr/bin/env bash
# define a var number then say number no equial to 10 do number inrease one by one but in the miedle if numbre equal to 4 echo bad luck and when is equal to 8 echo good luck.
number=1
while [[ $number -ne 10 ]]
do
	if [ "$number" == '4' ]; then
		echo "bad luck"
	elif [ "$number" == '8' ]; then
		echo "good luck"
	else	echo "Best School"
	fi
	((number++))
done
