#!/usr/bin/env bash
# 
number=1
while [[ $number -ne 9 ]]
do
        ((number++))
        echo "Best School"

	if [[ "$number" == '4' ]]; then
		echo "bad luck"
		continue

	elif [[ "$number" == '7' ]]; then
		echo "good luck"
		continue
	else
		continue
	fi
done
