#!/usr/bin/env bash
#create a var value 0 and while this is less equal  to 20 echo number 
number=0
while [[ $number -le 20 ]]
do
	echo "$number"
	case $number in
		4) echo "bad luck from China";; 
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((number++))
done
	
