#!/usr/bin/env bash
#Write a Bash script that displays:The content of the current directory-n a list format-Where only the part of the name after the first dash is displayed (refer to the example)

LIST=$(ls *)

for i in LIST; do echo "$LIST" | cut -d "-" -f2 ;done 
