#!/usr/bin/env bash
#
trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"; rm -rf /var/run/myscript.pid; exit' SIGINT
echo "$$" >> /var/run/myscript.pid
while ((2))
do
	echo "To infnity and beyond"
	sleep 2
done

